### ISSUE TITLE
xpose.nlmixr does not install on R 4.0.1

### ISSUE THREAD

**Issue by dervieux1** [nlmixrdevelopment/xpose.nlmixr#10]
Hello - The package does not install on R 4.0.1 - Any suggestion how to make it work?
package ‘xpose.nlmixr’ is not available (for R version 4.0.1)

**Comment by mattfidler** [comment]
For now you can use:

```R
devtools::install_github("nlmixredevlopment/xpose.nlmixr")
```

**Comment by dervieux1** [comment]
Matt - Thank you for the note:

devtools::install_github("nlmixredevlopment/xpose.nlmixr")
returns:
Error: Failed to install 'unknown package' from GitHub:
  HTTP error 404.
  Not Found

if I correct the typo to
devtools::install_github("nlmixrdevlopment/xpose.nlmixr")

same thing:

Error: Failed to install 'unknown package' from GitHub:
  HTTP error 404.
  Not Found

?

**Comment by mattfidler** [comment]
This is the correct command:

```r
devtools::install_github("nlmixrdevelopment/xpose.nlmixr")
```

**Comment by dervieux1** [comment]
thank you

**Comment by dervieux1** [comment]
There appears to be an issue with this package n1qn1

* installing *source* package ‘n1qn1’ ...
** package ‘n1qn1’ successfully unpacked and MD5 sums checked
** using staged installation
./configure: line 1734: n1qn1: command not found
checking for g77... no
checking for xlf... no
checking for f77... no
checking for frt... no
checking for pgf77... no
checking for cf77... no
checking for fort77... no
checking for fl32... no
checking for af77... no
checking for xlf90... no
checking for f90... no
checking for pgf90... no
checking for pghpf... no
checking for epcf90... no
checking for gfortran... no
checking for g95... no
checking for xlf95... no
checking for f95... no
checking for fort... no
checking for ifort... no
checking for ifc... no
checking for efc... no
checking for pgfortran... no
checking for pgf95... no
checking for lf95... no
checking for ftn... no
checking for nagfor... no
checking whether the Fortran 77 compiler works... no
configure: error: in `/private/var/folders/48/0_wk8zhj4mqd2nsfyx1jyyjw0000gq/T/RtmptVlnpJ/R.INSTALLed5452b9332f/n1qn1':
configure: error: Fortran 77 compiler cannot create executables
See `config.log' for more details
ERROR: configuration failed for package ‘n1qn1’
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/n1qn1’
Error: Failed to install 'xpose.nlmixr' from GitHub:
  (converted from warning) installation of package ‘n1qn1’ had non-zero exit status

**Comment by mattfidler** [comment]
Hi @dervieux1 

You need to install the Rtools 4.0 framework to have the gfortran compiler.

https://cran.r-project.org/bin/windows/Rtools/

This is occuring since n1qn1 does not have windows binaries for it currently.

**Comment by mattfidler** [comment]
If you are trying to install `xpose`, you will not have the `nlmixr` requirement for a functioning compiler.

**Comment by dervieux1** [comment]
> Hi @dervieux1
> 
> You need to install the Rtools 4.0 framework to have the gfortran compiler.
> 
> https://cran.r-project.org/bin/windows/Rtools/
> 
> This is occuring since n1qn1 does not have windows binaries for it currently.

I am working from a MacBook Pro.

**Comment by mattfidler** [comment]
Then you need the Mac Rtools:

https://cran.r-project.org/bin/macosx/tools/

**Comment by mattfidler** [comment]
In particular you need the fortran compiler:

https://github.com/fxcoudert/gfortran-for-macOS/releases

**Comment by dervieux1** [comment]
Thank you - the issue was resolved

**Comment by dervieux1** [comment]
MAtt:
Installed RTools on Windows: https://cran.r-project.org/bin/windows/Rtools/
when running nlmixr i get the following error:

In system(cmd) : 'make' not found
