### ISSUE TITLE
nlimxr crashes during SAEM model building

### ISSUE THREAD

**Issue by dervieux1** [nlmixrdevelopment/xpose.nlmixr#11]
I am running nlmixr and get the following error message during execution

Compiling RxODE equations...done.
Building SAEM model...done

then R session is aborted and terminated?

**Comment by mattfidler** [comment]
Sorry @dervieux1 , unless I can reproduce it I cannot debug it; 

Please provide a reproducible example. One way to do that is with reprex:

https://github.com/tidyverse/reprex
