### ISSUE TITLE
install xpose.nlmixr error

### ISSUE THREAD

**Issue by skyee1** [nlmixrdevelopment/xpose.nlmixr#12]
Hi:
I meet a surprised problem.

Error: package or namespace load failed for 'ggplot2' in library.dynam(lib, package, package.lib):
 DLL 'colorspace' not found: maybe not installed for this architecture?
Error : package 'ggplot2' could not be loaded
错误: 载入失败
停止执行
*** arch - x64
ERROR: loading failed for 'i386'
* removing 'D:/R/R-4.0.5/library/xpose.nlmixr'
Warning message:
In i.p(...) :
  installation of package ‘C:/Users/LENOVO~1/AppData/Local/Temp/RtmpWwrsdd/file144848a81d3d/xpose.nlmixr_0.1.5.tar.gz’ had non-zero exit status

my R versiongs 4.0.3.
my R have installed ggplot2,but it say load fail.

**Comment by mattfidler** [comment]
I would reinstall `ggplot2` and `colorspace`:

```r
install.packages(c("ggplot2", "colorspace")
```

**Comment by skyee1** [comment]
> I would reinstall `ggplot2` and `colorspace`:
> 
> ```r
> install.packages(c("ggplot2", "colorspace")
> ```

Thank you
when I have installed the **nlmixr** package(4,9,2021 publish) from CRAN rather than github,the **xpose.nlmixr** and **shinyMixR** installed successfully.I think I can use the UI to model PK/PD.

Thank you again!
Good Luck.
