### ISSUE TITLE
problem Installing xpose.nlmixr library

### ISSUE THREAD

**Issue by dharampaul** [nlmixrdevelopment/xpose.nlmixr#4]
Hi I have a problem installing "xpose.nlmixr' library. I am getting following error. sessionInfo is attached if need.
I have installed nlmixr using windows installer and everything else works so far as expected.
Any help will be highly appreciated.
regards,
Dharam
[sessionInfo.txt](https://github.com/nlmixrdevelopment/xpose.nlmixr/files/2400984/sessionInfo.txt)

> install_github("nlmixrdevelopment/xpose.nlmixr")
Downloading GitHub repo nlmixrdevelopment/xpose.nlmixr@master
from URL https://api.github.com/repos/nlmixrdevelopment/xpose.nlmixr/zipball/master
Installing xpose.nlmixr
Installation failed: cannot open the connection
Warning messages:
1: In normalizePath(path.expand(path), winslash, mustWork) :
  path[1]="c:\SVN\Wenping\dparser": The system cannot find the path specified
2: In read.dcf(path) :
  cannot open compressed file 'c:\SVN\Wenping\dparser/DESCRIPTION', probable reason 'No such file or directory'
>

**Comment by mattfidler** [comment]
Hi @dharampaul, xpose.nlmixr should be installed already.  Try

```R
library(xpose.nlmixr)
```

**Comment by dharampaul** [comment]
Thanks Matt, I am getting following error.
> library(xpose.nlmixr)
Error in library(xpose.nlmixr) : 
  there is no package called ‘xpose.nlmixr’

**Comment by dharampaul** [comment]
Also, when I tried shinymixR, I got same error.
> devtools::install_github("richardhooijmaijers/shinyMixR")
Downloading GitHub repo richardhooijmaijers/shinyMixR@master
from URL https://api.github.com/repos/richardhooijmaijers/shinyMixR/zipball/master
Installing shinyMixR
Installation failed: cannot open the connection
Warning messages:
1: In normalizePath(path.expand(path), winslash, mustWork) :
  path[1]="c:\SVN\Wenping\dparser": The system cannot find the path specified
2: In read.dcf(path) :
  cannot open compressed file 'c:\SVN\Wenping\dparser/DESCRIPTION', probable reason 'No such file or directory'

**Comment by mattfidler** [comment]
What happens when you try library(RxODE)?

**Comment by dharampaul** [comment]
> library(RxODE)
Warning message:
package ‘RxODE’ was built under R version 3.4.4 
>

**Comment by mattfidler** [comment]
Hi @dharampaul,

It seems like you are using a different RxODE version than what the installer provided, could you please outline the steps you used to setup nlmixr.

**Comment by dharampaul** [comment]
Hi Mat, I have two PC with windows 10. On other PC, I installed nlmixr from installer file (no customization). and I have RxODE_0.6-2. However, i got same error with following:
> install_github("nlmixrdevelopment/xpose.nlmixr")
Downloading GitHub repo nlmixrdevelopment/xpose.nlmixr@master
from URL https://api.github.com/repos/nlmixrdevelopment/xpose.nlmixr/zipball/master
Installing xpose.nlmixr
Installation failed: cannot open the connection
Warning messages:
1: In normalizePath(path.expand(path), winslash, mustWork) :
  path[1]="c:\SVN\Wenping\dparser": The system cannot find the path specified
2: In read.dcf(path) :
  cannot open compressed file 'c:\SVN\Wenping\dparser/DESCRIPTION', probable reason 'No such file or directory'
>

**Comment by dharampaul** [comment]
Is it easy to do installation on Linux? I am thinking to run Linux virtual machine.

**Comment by mattfidler** [comment]
Are you using Rstudio?  The RxODE you cite is old and isn't used on the installers.  For the 1.0 version you should have RxODE 0.8.  I'm working on a new release and installer for ACoP now.

**Comment by dharampaul** [comment]
Hi Mat, I downloaded installer from the link given in the user guide at (https://nlmixrdevelopment.github.io/nlmixr_bookdown/index.html) https://github.com/nlmixrdevelopment/nlmixr/releases/tag/v0.9.0-2
If this is not correct version, can you please advise from where should download latest version.
Thanks in advance.

**Comment by dharampaul** [comment]
I think I downloaded old version.
I will try new one from here
https://github.com/nlmixrdevelopment/nlmixr/releases/

**Comment by dharampaul** [comment]
Hi Mat, thanks for pointing to right direction. The latest version of nlmixr worked fine with all libraries loaded.

**Comment by mattfidler** [comment]
Awesome  @dharampaul 

Thank you for trying out nlmixr.
